name: Aula de GCS (PUCCAMPINAS)
on: push
jobs: 
  primeiro:
    runs-on: ubuntu-latest
    name: Primeiro Job Escrito
    steps:
     - run: echo "${{ github.event_name}} foi disparado"
     - run: echo "No ${{runner.os}}"
     - run: echo "Repositorio ${{ github_repository}} na branch ${{gitbun.ref}}"
     
     - name: Checkout o Repositorio
       uses: actions/checkout@v3
       
     -  
       
  segundo:
    runs-on: windows-lastest
    name: First
    steps: 
      - name: Criando Variaveis de ambiente
        env:
          VAR1: Isto é
          VAR2: GitHub Actions
        run: echo $VAR1 $VAR2

