name: Aula de GCS (PUCCAMPINAS)
on: push
    
jobs: 
  primeiro:
    runs-on: ubuntu-latest
    name: Primeiro Job Escrito
    steps: 
     - name: Mostrar Rodando
       run: echo teste
     - name: Mostra Rodando
       run: echo "${{ github.event_name }} foi disparado"
       
  segundo:
    runs-on: windows-lastest
    name: First
    steps: 
      - name: Criando Variaveis de ambiente
        env:
          VAR1: Isto é
          VAR2: GitHub Actions
        run: echo $VAR1 $VAR2

  terceiro:
    runs-on: ubuntu-lastest
    name: Terceiro
    steps:
      - name: Terceiro
        run: echo "${{ github.event_name }} foi disparado
